### PR TITLE
Add setup session to Noxfile for installing dependencies

### LINKED ISSUE #811: include all supported python version in dockerfile and support nox
Currently our devcontainers don't include support for nox and don't have the other python versions that nox tests against.

#### to fix

- change the image to `thekevjames/nox`
- run `nox -s setup`

### PR DESCRIPTION
**Pull request by OsamaRab3**
fix  #811

#### Type of Issue

- [ ] :bug: (bug)
- [ ] :book: (Documentation)
- [ ] :arrow_up: (Update)
- [ ] :dizzy: (New Feature)
- [ ] :radioactive: (Deprecation)
- [ ] :no_entry_sign: (Removal)
- [ ] :hammer_and_wrench: (Refactor)

#### Changes have been Documented (If Applicable)

- [x] YES - Changes have been documented

#### Changes have been Tested

- [x] YES - Changes have been tested

### CODE REVIEW

**Review by kjaymiller — CHANGES_REQUESTED** [review]
Can you add a screenshot of this working. I'm unable to load the codespace with this change?

**Comment by OsamaRab3** [comment]
> Can you add a screenshot of this working. I'm unable to load the codespace with this change?

image

**Comment by kjaymiller** [comment]
Was this with VS Code Dev Containers or locally or Codespaces or your local terminal.

**Comment by OsamaRab3** [comment]
> Was this with VS Code Dev Containers or locally or Codespaces or your local terminal.

 I ran the nox -s setup command  locally in Vs code

**Comment by kjaymiller** [comment]
> > Was this with VS Code Dev Containers or locally or Codespaces or your local terminal.
> 
> I ran the nox -s setup command locally in Vs code. If there is anything else that needs to be done, please let me know

This means that you can run the steps to install things locally which is good. 

That said when you try to follow the steps in a codespace it doesn't work.

https://github.com/user-attachments/assets/6113e0b6-48c9-4186-90df-728e6a2861fa

**Comment by OsamaRab3** [comment]
> This means that you can run the steps to install things locally which is good.
> 
> That said when you try to follow the steps in a codespace it doesn't work.
> 
>  CleanShot.2024-10-07.at.08.07.08.-.01.mp4

When trying to install the required packages in Codespaces. I get errors related to version conflicts and missing packages.
Why this is happening and what steps I should take?

**Comment by kjaymiller** [comment]
> When trying to install the required packages in Codespaces. I get errors related to version conflicts and missing packages. Why this is happening and what steps I should take?

Not sure. This (trying to deploy your changes) was the first time I ran into this issue

**Pull request closed without merging**
