### PR TITLE
Reduced the size of the contributors image

### LINKED ISSUE #377: reduce the size of the contributors image
as the list grows we want to make sure that the list isn't taking up too much space on the readme

per - https://allcontributors.org/docs/en/bot/configuration - update the `imageSize` in the `allcontributorsrc.json` file

### PR DESCRIPTION
**Pull request by Tashuuuu**
Fixes #377 

**Proposed Changes**

Changed the ```imageSize``` from 100 to 57 in the ```allcontributorsrc.json``` file

### CODE REVIEW

**Comment by Mahhheshh** [comment]
Could you also attend to #378 within the same pull request,

**Comment by kjaymiller** [comment]
I would be open to either a joint PR on this or just a singular one for each

**Comment by Tashuuuu** [comment]
Attended #378 within PR #384

**Comment by kjaymiller** [comment]
@all-contributors please add Tashuuuu for tool

**Pull request merged**
